/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CimaReputacion {
      
    export type PerfilLocatarioStruct = {activo: boolean, totalTransacciones: BigNumberish, volumenTotal: BigNumberish, primeraTx: BigNumberish, ultimaTx: BigNumberish, disputasAbiertas: BigNumberish, disputasResueltas: BigNumberish}

    export type PerfilLocatarioStructOutput = [activo: boolean, totalTransacciones: bigint, volumenTotal: bigint, primeraTx: bigint, ultimaTx: bigint, disputasAbiertas: bigint, disputasResueltas: bigint] & {activo: boolean, totalTransacciones: bigint, volumenTotal: bigint, primeraTx: bigint, ultimaTx: bigint, disputasAbiertas: bigint, disputasResueltas: bigint }
  

    export type TransaccionStruct = {locatario: AddressLike, monto: BigNumberish, timestamp: BigNumberish, categoria: BigNumberish}

    export type TransaccionStructOutput = [locatario: string, monto: bigint, timestamp: bigint, categoria: bigint] & {locatario: string, monto: bigint, timestamp: bigint, categoria: bigint }
  
    }

  export interface CimaReputacionInterface extends Interface {
    getFunction(nameOrSignature: "abrirDisputa" | "actualizarAgente" | "agente" | "obtenerPerfil" | "obtenerTransaccion" | "obtenerTxsLocatario" | "owner" | "perfiles" | "registrarLocatario" | "registrarPago" | "resolverDisputa" | "totalTransaccionesGlobal" | "transacciones" | "txsPorLocatario"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgenteActualizado" | "DisputaAbierta" | "DisputaResuelta" | "LocatarioRegistrado" | "PagoRegistrado"): EventFragment;

    encodeFunctionData(functionFragment: 'abrirDisputa', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'actualizarAgente', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'agente', values?: undefined): string;
encodeFunctionData(functionFragment: 'obtenerPerfil', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'obtenerTransaccion', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'obtenerTxsLocatario', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'perfiles', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registrarLocatario', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registrarPago', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolverDisputa', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalTransaccionesGlobal', values?: undefined): string;
encodeFunctionData(functionFragment: 'transacciones', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'txsPorLocatario', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'abrirDisputa', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'actualizarAgente', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agente', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obtenerPerfil', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obtenerTransaccion', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obtenerTxsLocatario', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'perfiles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registrarLocatario', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registrarPago', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolverDisputa', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTransaccionesGlobal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transacciones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'txsPorLocatario', data: BytesLike): Result;
  }

  
    export namespace AgenteActualizadoEvent {
      export type InputTuple = [anterior: AddressLike, nuevo: AddressLike];
      export type OutputTuple = [anterior: string, nuevo: string];
      export interface OutputObject {anterior: string, nuevo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputaAbiertaEvent {
      export type InputTuple = [locatario: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [locatario: string, timestamp: bigint];
      export interface OutputObject {locatario: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputaResueltaEvent {
      export type InputTuple = [locatario: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [locatario: string, timestamp: bigint];
      export interface OutputObject {locatario: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LocatarioRegistradoEvent {
      export type InputTuple = [locatario: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [locatario: string, timestamp: bigint];
      export interface OutputObject {locatario: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PagoRegistradoEvent {
      export type InputTuple = [txId: BigNumberish, locatario: AddressLike, monto: BigNumberish, categoria: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [txId: bigint, locatario: string, monto: bigint, categoria: bigint, timestamp: bigint];
      export interface OutputObject {txId: bigint, locatario: string, monto: bigint, categoria: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CimaReputacion extends BaseContract {
    
    connect(runner?: ContractRunner | null): CimaReputacion;
    waitForDeployment(): Promise<this>;

    interface: CimaReputacionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    abrirDisputa: TypedContractMethod<
      [_locatario: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    actualizarAgente: TypedContractMethod<
      [_nuevoAgente: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    agente: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    obtenerPerfil: TypedContractMethod<
      [_locatario: AddressLike, ],
      [CimaReputacion.PerfilLocatarioStructOutput],
      'view'
    >
    

    
    obtenerTransaccion: TypedContractMethod<
      [_txId: BigNumberish, ],
      [CimaReputacion.TransaccionStructOutput],
      'view'
    >
    

    
    obtenerTxsLocatario: TypedContractMethod<
      [_locatario: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    perfiles: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {activo: boolean, totalTransacciones: bigint, volumenTotal: bigint, primeraTx: bigint, ultimaTx: bigint, disputasAbiertas: bigint, disputasResueltas: bigint }],
      'view'
    >
    

    
    registrarLocatario: TypedContractMethod<
      [_locatario: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registrarPago: TypedContractMethod<
      [_locatario: AddressLike, _monto: BigNumberish, _categoria: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolverDisputa: TypedContractMethod<
      [_locatario: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalTransaccionesGlobal: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transacciones: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint] & {locatario: string, monto: bigint, timestamp: bigint, categoria: bigint }],
      'view'
    >
    

    
    txsPorLocatario: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'abrirDisputa'): TypedContractMethod<
      [_locatario: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'actualizarAgente'): TypedContractMethod<
      [_nuevoAgente: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'agente'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'obtenerPerfil'): TypedContractMethod<
      [_locatario: AddressLike, ],
      [CimaReputacion.PerfilLocatarioStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'obtenerTransaccion'): TypedContractMethod<
      [_txId: BigNumberish, ],
      [CimaReputacion.TransaccionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'obtenerTxsLocatario'): TypedContractMethod<
      [_locatario: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'perfiles'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {activo: boolean, totalTransacciones: bigint, volumenTotal: bigint, primeraTx: bigint, ultimaTx: bigint, disputasAbiertas: bigint, disputasResueltas: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'registrarLocatario'): TypedContractMethod<
      [_locatario: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registrarPago'): TypedContractMethod<
      [_locatario: AddressLike, _monto: BigNumberish, _categoria: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolverDisputa'): TypedContractMethod<
      [_locatario: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalTransaccionesGlobal'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transacciones'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint] & {locatario: string, monto: bigint, timestamp: bigint, categoria: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'txsPorLocatario'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'AgenteActualizado'): TypedContractEvent<AgenteActualizadoEvent.InputTuple, AgenteActualizadoEvent.OutputTuple, AgenteActualizadoEvent.OutputObject>;
getEvent(key: 'DisputaAbierta'): TypedContractEvent<DisputaAbiertaEvent.InputTuple, DisputaAbiertaEvent.OutputTuple, DisputaAbiertaEvent.OutputObject>;
getEvent(key: 'DisputaResuelta'): TypedContractEvent<DisputaResueltaEvent.InputTuple, DisputaResueltaEvent.OutputTuple, DisputaResueltaEvent.OutputObject>;
getEvent(key: 'LocatarioRegistrado'): TypedContractEvent<LocatarioRegistradoEvent.InputTuple, LocatarioRegistradoEvent.OutputTuple, LocatarioRegistradoEvent.OutputObject>;
getEvent(key: 'PagoRegistrado'): TypedContractEvent<PagoRegistradoEvent.InputTuple, PagoRegistradoEvent.OutputTuple, PagoRegistradoEvent.OutputObject>;

    filters: {
      
      'AgenteActualizado(address,address)': TypedContractEvent<AgenteActualizadoEvent.InputTuple, AgenteActualizadoEvent.OutputTuple, AgenteActualizadoEvent.OutputObject>;
      AgenteActualizado: TypedContractEvent<AgenteActualizadoEvent.InputTuple, AgenteActualizadoEvent.OutputTuple, AgenteActualizadoEvent.OutputObject>;
    

      'DisputaAbierta(address,uint256)': TypedContractEvent<DisputaAbiertaEvent.InputTuple, DisputaAbiertaEvent.OutputTuple, DisputaAbiertaEvent.OutputObject>;
      DisputaAbierta: TypedContractEvent<DisputaAbiertaEvent.InputTuple, DisputaAbiertaEvent.OutputTuple, DisputaAbiertaEvent.OutputObject>;
    

      'DisputaResuelta(address,uint256)': TypedContractEvent<DisputaResueltaEvent.InputTuple, DisputaResueltaEvent.OutputTuple, DisputaResueltaEvent.OutputObject>;
      DisputaResuelta: TypedContractEvent<DisputaResueltaEvent.InputTuple, DisputaResueltaEvent.OutputTuple, DisputaResueltaEvent.OutputObject>;
    

      'LocatarioRegistrado(address,uint256)': TypedContractEvent<LocatarioRegistradoEvent.InputTuple, LocatarioRegistradoEvent.OutputTuple, LocatarioRegistradoEvent.OutputObject>;
      LocatarioRegistrado: TypedContractEvent<LocatarioRegistradoEvent.InputTuple, LocatarioRegistradoEvent.OutputTuple, LocatarioRegistradoEvent.OutputObject>;
    

      'PagoRegistrado(uint256,address,uint256,uint8,uint256)': TypedContractEvent<PagoRegistradoEvent.InputTuple, PagoRegistradoEvent.OutputTuple, PagoRegistradoEvent.OutputObject>;
      PagoRegistrado: TypedContractEvent<PagoRegistradoEvent.InputTuple, PagoRegistradoEvent.OutputTuple, PagoRegistradoEvent.OutputObject>;
    
    };
  }