/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CimaReputacion } from './CimaReputacion.js';
export * as factories from './factories/index.js';
export { CimaReputacion__factory } from './factories/CimaReputacion__factory.js';